name: flutter_fawry_pay_platform_interface
description: A common platform interface for the flutter_fawry_pay plugin.
version: 0.0.1
homepage: https://github.com/ShadyBoshra2012/flutter_fawry_pay

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter